### ISSUE TITLE
Can not build WASM with Bevy

### ISSUE THREAD

**Issue by tungtose** [MOZGIII/xwebtransport#35]
Thank you for your efforts to make this lib happen!

I am trying to play with experimenting **xwebtransport** with **bevy**, but unfortunately I can't  build it into WASM and got this error: 

![image](https://github.com/MOZGIII/xwebtransport/assets/72777913/82b2aabd-4927-496c-b39b-49752db7834d)

Since I am already pull the lib and try to build and run all the test and it was successfully, I think it's some what I'm doing wrong with my _Cargo.toml_

Here is my _Cargo.toml_ file: 

![image](https://github.com/MOZGIII/xwebtransport/assets/72777913/63b32ffd-8078-4a8e-9039-4c56d37b8368)

I think I need to put any features flag? But I'm not found any features flag in your lib.
Do you have any suggestion?

**Comment by MOZGIII** [comment]
There are tests that would break if this crate had some features missing, so it is really odd that you are experiencing issues... That said, let me investigate for a bit.

I am using this with bevy myself, so it should work, at least for me it does with a similar setup.

**Comment by MOZGIII** [comment]
`xwebtransport-web-sys` does activate the `WebTransport` feature of the `web-sys` crate.

So, my suspicion is the `web-sys` crate you are using might be older than the one I have been testing against. Or yours is newer and they've changed something that broke `xwebtransport-web-sys` on your end, but not in the CI (which I ran yesterday).

**Comment by MOZGIII** [comment]
Can you try `cargo update -p web-sys`?

**Comment by tungtose** [comment]
I don't have **web-sys** crate in my project yet, just  **bevy** and **xwebtransport** to test.

I try to put **web-sys** exactly as your lib does but still luck, still not enable the web-sys web transport features: 

![image](https://github.com/MOZGIII/xwebtransport/assets/72777913/3002735e-1c63-466e-b55e-a4d919b5435f)

Yes I also try to run your CI test and it's Ok as well.

Could you give small example how you integrate **xwebtransport** with **bevy**

**Comment by tungtose** [comment]
> Can you try `cargo update -p web-sys`?

Yes, I did that, but the output is still the same

**Comment by MOZGIII** [comment]
The only thing I can think of is a missing `resolver = "2"` at the workspace-level `Cargo.toml` if you are using the workspaces. If you don't - well, then I have no idea how it's possible.

You could try specifying the `xwebtransport-web-sys` dependency explicitly together with the `web-sys` and enabling the `WebTransport` feature-flag there (i.e. just like how you have it above). This would eliminate some potential bugs.

I am integrating the `xwebtransport` through a whole `xplatform` layer (that is not open just yet, and is mostly project-specific as all it does it ties all the cross-platform modules together with a unified configuration layer). It should, however, work either way.

**Comment by MOZGIII** [comment]
If you can share your code I can jump in and try making it work for you. I am curious as to what it could be.

Also, try doing `rm -rf target` - sometimes it helps work around the bugs in rust incremental compilation.

**Comment by tungtose** [comment]
Sure, I just push the code on this [repo](https://github.com/tungtose/test-xwebtransport)


> If you can share your code I can jump in and try making it work for you. I am curious as to what it could be.
> 
> Also, try doing `rm -rf target` - sometimes it helps work around the bugs in rust incremental compilation.

Yes, I did it before

**Comment by MOZGIII** [comment]
Ah, yes, can you try with nightly rust? WebTransport is unstable, so maybe `web-sys` insists on both feature and nightly rust?

**Comment by tungtose** [comment]
I just try it

![image](https://github.com/MOZGIII/xwebtransport/assets/72777913/29ea1ce6-7184-40f2-885f-f854fcd4d687)

**Comment by tungtose** [comment]
I just try to put project in the same level with your crate , and resolve dependencies through **path**. 
![image](https://github.com/MOZGIII/xwebtransport/assets/72777913/93aca643-98a7-46c8-b4b4-a6a54c7e04cc)

Then it compile successfully. Do you have any idea

**Comment by MOZGIII** [comment]
Found it: https://github.com/MOZGIII/xwebtransport/blob/master/.cargo/config.toml
I forgot about this one :D You have to pass this `cfg` too.

**Comment by tungtose** [comment]
It's compiled now
Thank you for your help!
